services:

  web:
    build: .
    command: python run_server.py
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:6
    ports:
      - "6379:6379"
