# Generated by Django 5.2 on 2025-04-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_message_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_sender',
            field=models.BooleanField(default=False),
        ),
    ]
